### ISSUE TITLE
[Feature request]: SSID/Password update

### ISSUE THREAD

**Issue by mittal07abhilash** [sblantipodi/firefly_luciferin#100]
### Is your feature request related to a problem? Please describe

I recently changed the password of my WiFi for security reasons and I was unable to update the same for Glowworm Luciferin installed on a custom ESP8266 board since it does not have a micro-USB port (installed the firmware by soldering wire on to the ESP8266 12-E Chip and connecting them to a CP2102 USB to TTL USB UART Module).

### Describe the solution you'd like

Since Gloowworm Luciferin is able to push firmware updates to the Firefly device through wireless communication, there must be a way to set SSID/password for the Firefly device to connect to the WiFI.

**Comment by sblantipodi** [comment]
Hi, thanks for using Luciferin and for sharing new ideas.
password management is something that will be improved in the next future :)
