### ISSUE TITLE
[Feature request]: MQTT Auto Discovery to facilitate the configuration of devices in Home Assistant.

### ISSUE THREAD

**Issue by raybantracing** [sblantipodi/firefly_luciferin#101]
### Is your feature request related to a problem? Please describe

Hi,
I have a lot of Luciferin devices because I have multiple computers at home, 
add all these devices to Home Hassistant is time consuming since you need to manually edit all the MQTT topics to correctly match the device in use.

Have you ever considered adding an MQTT Auto Discovery feature in order to automate this setup?

**Comment by sblantipodi** [comment]
Hi @raybantracing,
thanks for your suggestion... 

As discussed on Discord I'm implementing this feature right now and it will be available soon...

Thanks
Davide
