### ISSUE TITLE
[Bug]: Power Mode with Solid led colour

### ISSUE THREAD

**Issue by lordraiden** [sblantipodi/firefly_luciferin#107]
### Firefly Luciferin version

2.10.10

### Glow Worm Luciferin version

5.9.7

### Firmware type

FULL

### What is the stream method?

WiFi Stream

### How to reproduce

While using it with solid colour and power save to 2min, I usually get the leds automatically off if am in a very black screens. I'm using an oled so I tend to have everything dark

If I go to a white page and maximise the windows the leds switch on again.

It looks like the power save mode in solid led mode still uses the "screen capture" instead something simple like mouse movement or something like that. I think it would be better to change this behaviour to use a trigger more realistic. Windows must have idle events, or timers or things like that.

**Comment by sblantipodi** [comment]
@lordraiden  power saving analyzes the screen, if nothing changed on the screen for two minutes it turns off the lights.
If you don't like this behaviour, you can disable power saving or set it to 5 minutes or 10 minutes.
Monitor technology does not affect screen capture
All in all that is the power saving feature, if you are not using the pc it turns off the lights.
If you want that lights stays on all the time, Simply disable power saving

**Comment by lordraiden** [comment]
> @lordraiden power saving analyzes the screen, if nothing changed on the screen for two minutes it turns off the lights. If you don't like this behaviour, you can disable power saving or set it to 5 minutes or 10 minutes. Monitor technology does not affect screen capture All in all that is the power saving feature, if you are not using the pc it turns off the lights. If you want that lights stays on all the time, Simply disable power saving

Ok, I understand now, thanks

**Comment by sblantipodi** [comment]
Rereading your issue I better understood the request :D
You would  like to see a different trigger than screen capture, like a mouse movement.
it has sense. I'll do it that way. thanks for the suggestion @lordraiden

**Comment by lordraiden** [comment]
Yes, that was the issue the fact that the edge of the screen is black doesn't mean that I'm idle, I could increase the time as you suggested but have a different trigger for the idle than the colour of the screen would be better.
