### ISSUE TITLE
[Feature request]:  Smoothing

### ISSUE THREAD

**Issue by brekotis** [sblantipodi/firefly_luciferin#109]
### Is your feature request related to a problem? Please describe

I would like to see a function to adjust the smoothing of the color change, as it is done in ambibox. Sometimes in games, when the color changes very quickly, very sharp unpleasant blinks occur on the side.

**Comment by sblantipodi** [comment]
Hi @brekotis this feature request has already been discussed some time ago here #80 

The features will be released very soon in the next release.
