### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by ikrowni** [sblantipodi/firefly_luciferin#11]
From the power supply barrel jack I have a red wire going to 3v3 and white wire going to Ground on the wemos d1 mini.

I have another red wire coming from the barrel jack going to the 5v and a white wire to the GND of the led strip. 

I have a green wire going from D1 of the wemos mini to the data in of the led strip.

After opening the windows software I set the proper amount of LEDs for each section. I left the next tab default, then I entered my mqtt server which is run as an add-on on home assistant.

When I right click the icon in the bottom right and click (start) nothing happens.

**Comment by sblantipodi** [comment]
hi @ikrowni thanks for opening the issue.
I don't think that you should connect a 5V input to the 3.3V PIN of your D1 Mini.
D1 Mini have a 5V PIN, you can use it for the 5V input.

Is your D1 Mini connected to the Wifi/MQTT network? have you followed this guide here?
https://github.com/sblantipodi/firefly_luciferin/wiki/Remote-Access
Are you sure you entered the correct value for WiFi and MQTT?

if no, please follow the steps I linked, be sure to insert the correct input.

In the Firefly Luciferin software have you selected the Enable MQTT and MQTT Stream checkbox?
Note: that checkboxes requires a software restart to be effective.

please go to home assistant and try to turn on the led strip using the light entity you created.
select the solid effect and turn it on, does it turn on now?

**Comment by ikrowni** [comment]
Okay I seem to have it working now. But when I run the test image from within the software the colors aren't properly matching.

I have 32 leds going across the top and 32 going across the bottom. Then there are 19 on the left and 19 on the right.

I have the software set as 

32 top
19 left
19 right
16 bottom left
16 bottom right

I don't see anyway to like offset the colors to match up with the test image.

**Comment by sblantipodi** [comment]
Nice done @ikrowni 
It's almost done.  
What's your monitor resolution? What is your os scaling 125%,150%?  
What do you mean by the colours aren't properly matching? Do you see red, green, blu, red, green, blu LEDs but sometimes you see some errors like two red LEDs or something like that?
If you want you can share a photo.

**Comment by ikrowni** [comment]
Windows shows that the monitor scale is set to 100% same as in the settings for luciferin.

My monitor is 1440p 

When I bring the test image up from within the luciferin program it shows the colors along with numbers. Are the numbers indicative of the led number?

**Comment by sblantipodi** [comment]
> Windows shows that the monitor scale is set to 100% same as in the settings for luciferin.
> 
> My monitor is 1440p
> 
> When I bring the test image up from within the luciferin program it shows the colors along with numbers. Are the numbers indicative of the led number?

Mmm. It's strange, 1440p is the resolution I'm using right now.
Yes the numbers in that test image must match the number of your LEDs. It should match the LEDs number you configured in the first tab.
Please note that you need to consider the orientation of the led strip, this depends on how you connected the strip, clockwise or anticlockwise, this setting can be configured in the first tab and requires a software restart after you save and close the settings.

**Comment by ikrowni** [comment]
If looking at the monitor LEDs start at the bottom right then go left, up, right, down.

Here's an image where it shows that led 1 starts near the center of the bottom strip.

https://imgur.com/gallery/JaCD0kk

**Comment by sblantipodi** [comment]
@ikrowni you have two options.
1) **The preferred one** is to correctly attach the LED strip behind your monitor, first led should start in the bottom half of the monitor as you see in the test image.
2) Correct the automatically generated LED matrix manually.
You can find that LED matrix in ~/Documents/FireflyLuciferin/FireflyLuciferin.yaml, please note that the first option is the preferred one

**Comment by ikrowni** [comment]
Alright I set it up as per the test page configuration and it seems to be working great now. Thanks for this.

**Comment by sblantipodi** [comment]
Thanks for letting me know. Closing the issue but feel free to open a new issue if you need it.
