### ISSUE TITLE
[Feature request]: Add WLED support.

### ISSUE THREAD

**Issue by makersteto** [sblantipodi/firefly_luciferin#113]
### Is your feature request related to a problem? Please describe

Hello,
I'm an old WLED user but I'm currently using Luciferin as my main software to create an ambilight clone.

I think that Luciferin is the best in class ambilight clone software for PC but I haven't understood how to integrate it with WLED.

Is it possible to integrate Firefly Luciferin with WLED?
https://github.com/sblantipodi/firefly_luciferin

If the answer is no,
do you consider supporting WLED in the future?

**Comment by sblantipodi** [comment]
I answered there.

**Comment by sixtyfive** [comment]
Issue is still open over in the WLED Issues. Was this perhaps only closed by the bot because it was forgotten about?

**Comment by sblantipodi** [comment]
@sixtyfive thanks for your interest in Luciferin. 
as described in the WLED issue, I have no interest in adding WLED support.

WLED is a great software but it was made for a different purpose and I don't see how adding WLED support may benefit Luciferin's users.
Luciferin is deeply integrated with its companion firmware, supporting WLED will break too many features.
