### ISSUE TITLE
[Feature request]: manual IP entry

### ISSUE THREAD

**Issue by Gibletron** [sblantipodi/firefly_luciferin#132]
### Is your feature request related to a problem? Please describe

My PC and ESP32 live in separate VLANs/Subnets
Because of this the auto Discovery of the the ESP doesn't function and I'm unable to use the UDP Stream option.

### Describe the solution you'd like

Allow a user to manually enter the IP of the ESP32

### Describe alternatives you've considered

Using USB is an alternative, but with the slow FPS I would not prefer to use this long term

**Comment by sblantipodi** [comment]
as commented on Discord, the issue has been tested by the opener... ready for release.
