### ISSUE TITLE
Flickering at certain times

### ISSUE THREAD

**Issue by ikrowni** [sblantipodi/firefly_luciferin#16]
While running the fluid simulation test on youtube I'm seeing some of the colors flickering. It doesn't happen with all of the colors though. Seems like yellows and greens do it the most. But I don't think it's a power issue as bright white doesn't flicker at all.

5v 10a power supply
Wemos d1 mini
107 LEDs Total

Thanks for any help this is the 4th monitor I've done with your project and I love it.

**Comment by sblantipodi** [comment]
@ikrowni thanks for the kind words.
are you using GlowWorm Luciferin FULL or LIGHT?

If you are using FULL firmware, do you use MQTT stream?

Can you post a video of the LEDs while flickering? Is this something that happens always or something that happens one time every N minutes?

**Comment by ikrowni** [comment]
I'm using the FULL firmware with mqtt stream like the other monitors I've done. I'm not home to make a video right this second but it seems like it's everytime a green or yellow color happens. I paused the video at a yellow section and it just kept happening until I resumed the video and the color swapped to something else.

**Comment by sblantipodi** [comment]
@ikrowni 
is this a problem that happens on every monitor you are running luciferin?
are you using a WS2812B strip?

are you using a level shifter? if yes, can you post a photo please?

thanks

**Comment by ikrowni** [comment]
This is the first time I've had the problem. I'm using the same ws2812b LEDs I've always used but I did swap to a different d1 mini brand. I've not added a level shifter do you think that could be the problem?

**Comment by sblantipodi** [comment]
> This is the first time I've had the problem. I'm using the same ws2812b LEDs I've always used but I did swap to a different d1 mini brand. I've not added a level shifter do you think that could be the problem?

yes, that could be the problem. it seems an electrical problem more than a software ones.
I really suggest to use a level shifter and a 220ohm resistance.

WS2812B chip get the signal with a voltage difference between the input voltage and the voltage received on the digital pin.
D1 Mini isn't able to give enough voltage on that pin for WS2812B, as you can see it works but it isn't 100% reliable.

I suggest to use something like this:
https://www.amazon.com/KeeYees-Channels-Converter-Bi-Directional-Shifter/dp/B07LG646VS/ref=sr_1_1?dchild=1&keywords=3.3V+to+5V+level+shifter&qid=1599343291&sr=8-1

along with a 220ohm resistance that helps preventing the digital pin to be damaged by some voltage spikes that may occur.

here you can find how to connect those components.
https://github.com/sblantipodi/glow_worm_luciferin/blob/master/assets/img/ambilight_bb.png

**Comment by ikrowni** [comment]
Okay thanks I'll mark this closed for now until I get the necessary parts to repair this one and see if it fixes the issues.

**Comment by sblantipodi** [comment]
@ikrowni thanks for the feedback. feel free to reopen a new issue in case the problem persist.
thanks.

**Comment by sblantipodi** [comment]
@ikrowni I have one user on Discord that is complaining about a similar issue.
level shifter is really needed for this project and should help, it seems that the discor user solved by replacing the led strip with a better quality one.

**Comment by ikrowni** [comment]
Im using btf lighting which manufacturer would you suggest?

**Comment by sblantipodi** [comment]
> Im using btf lighting which manufacturer would you suggest?

Mmm. I use bfg lighting and never had problems, many users around the project uses bft lighting and no problem.
Hope that level shifter will solve your problem :)
