### ISSUE TITLE
[Feature request]: Restart screen capture automatically after MQTT reconnect

### ISSUE THREAD

**Issue by karl0ss** [sblantipodi/firefly_luciferin#162]
### Is your feature request related to a problem? Please describe

When screen capture stops due to disconnection of the network/mqtt server display capture is not restarted

### Describe the solution you'd like

An option to automatically restart screen capture after restored network/mqtt server connection.

**Comment by sblantipodi** [comment]
Next release will have this feature implemented. Thanks for sharing your idea about a useful improvement.

**Comment by karl0ss** [comment]
Thanks for the great app!
