### ISSUE TITLE
(Feature Request) Luciferin add-on for home assistant

### ISSUE THREAD

**Issue by ikrowni** [sblantipodi/firefly_luciferin#17]
Would it be possible to get a luciferin add-on going in home assistant that could handle multiple instances of monitors with varying led lengths?

**Comment by sblantipodi** [comment]
> Would it be possible to get a luciferin add-on going in home assistant that could handle multiple instances of monitors with varying led lengths?

Hi @ikrowni thanks for your requests, I always appreciate new ideas.

Can you explain me better what is the purpose?
Do you want to have 1 PC and multiple monitors or multiple PCs with multiple monitors?

**Comment by ikrowni** [comment]
Multiple pcs/tvs throughout the house

**Comment by sblantipodi** [comment]
I don't think that you are an idiot, feel free to ask what ever you want here, 
don't be afraid to say "inaccuracies", always glad to hear the voice of the users :D
