### ISSUE TITLE
Incorrect color displayed?

### ISSUE THREAD

**Issue by Socrate214** [sblantipodi/firefly_luciferin#19]
updated to 1.4.0 today and noticed that the colors do not seem to be displayed correctly anymore, for instance when my screen shows a bright red, the LED will show green.
was not the case before the update but I could not find a setting to adjust the colors at all

**Comment by sblantipodi** [comment]
Do you updated the firmware to 4.2.1?
Firmware should always be upgraded when you upgrade the pc software.

**Comment by sblantipodi** [comment]
@Socrate214 I will add a message that inform users to upgrade the firmware when the pc software is updated.
This is not so clear. Thanks for pointing it out.
Light firmware does not support automatic upgrade, full version does.

Closing the issue, feel free to reopen it if you still have the problem.

Thanks!
