### ISSUE TITLE
[Feature request]: Availability through Flathub or as a Flatpak (Linux)

### ISSUE THREAD

**Issue by mawoka-myblock** [sblantipodi/firefly_luciferin#207]
### Is your feature request related to a problem? Please describe

As I'm using Fedora Kionite, I want to use flatpaks where ever possible.

### Describe alternatives you've considered

Maybe AppImages, but they don't integrate well. But I'd still prefer those over the rpm package.

**Comment by sblantipodi** [comment]
I leave this open as a feature request if someone wants to contribuite to it :)

**Comment by sblantipodi** [comment]
@mawoka-myblock 
https://flathub.org/apps/org.dpsoftware.FireflyLuciferin

**Comment by mawoka-myblock** [comment]
How cool is that?! Thank you do much for your effort!
