### ISSUE TITLE
Shut off lights when computer turned off

### ISSUE THREAD

**Issue by ikrowni** [sblantipodi/firefly_luciferin#21]
What would be the best method to shut the lights off after the computer is shut off? As of right now the lights just turn full bright white when the computer turns off and i have to unplug the power to them.

**Comment by sblantipodi** [comment]
Please update Firefly Luciferin PC software to the latest 1.4.2 version  
and Glow Worm Luciferin firmware to the latest 4.2.3 version.

You should solve the problem this way, please let me informed it the update will solve your issue.
Thanks

**Comment by ikrowni** [comment]
Seems to be working thanks.

**Comment by sblantipodi** [comment]
Thank you for letting me know @ikrowni  

I'm going to close the issue, feel free to reopen it if the problem persists.
