### ISSUE TITLE
Other Arduino Board alternative?

### ISSUE THREAD

**Issue by DrSaad77** [sblantipodi/firefly_luciferin#23]
Hi, I got an AmbiLight set up on the back of my monitor using AmbiBox/Prismatik. I used Arduino Nanoe. I would like to give a try to this soft, but it is not working. Also in Devices window on settings of  Firefly Luciferin my board is not present. Of course I made sure to select the right Port the arduino board is connected to the PC + the board is setted to work with 115200, that the max available to select from Device Manager of Windows. 
I suppect it is related to the fact that the scretch uploaded at the moment to my Nano board is not supposed to work with Firefly Luciferin. Of course it is a guess. 
So maybe some more expert user can give some ideas?
Thx

**Comment by sblantipodi** [comment]
@DrSaad77 hi, thanks for your interest in the project.
Luciferin does not support Nano Boards at the moment.
If you want to give a try to the ESP8266 D1 Mini supported baord they are very powerful, cheap and with builtin wifi.

https://www.amazon.com/IZOKEE-NodeMcu-Internet-Development-Compatible/dp/B076F52NQD/ref=sr_1_1_sspa?dchild=1&keywords=esp8266+d1+mini&qid=1601682812&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExSVRZR1ZEVzhYU01SJmVuY3J5cHRlZElkPUEwMTA2MzYwMTY1QkhMVUhEV0Q0UCZlbmNyeXB0ZWRBZElkPUEwMjM3MTc4MkpVR0ZVRzNVRFhIQiZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=

**Comment by DrSaad77** [comment]
Ah ok, thx you very much, I actually got a WeMos D1 Mini or ESP8266 D1 Mini, it is the same. But since the Nano is already solder and installed at the back of the monitor, I wanted to give a try to the soft as I said previously...
Kind of lazy at the moment to remove it and solder the WeMos D1 Mini lol, plus I reserve it for another preject where Wifi avaibility will be more usefull than an AmbiLight of the back of a monitor... For te monitor, I tried back while with Node MCU 8622 which got wifi, but I found it a bit pain to tweak through wifi... just mean it is easier with PC...
I read and also found out that Firefly Luciferin + WeMos D1 Mini can be used for other project than ambiLight for monitor, at this moment a wif compatible board seems more suited 😁
Hope it future compatibility for other board will be add to firefly since there are not very far from each other 😉 of course it is a guess 😅

**Comment by sblantipodi** [comment]
@DrSaad77 Luciferin is a fast project that will grow fast. 
There are many new features planned for the next future, adding boards support is not in the current release plan.
I find that ESP8266 is the best board for the purpose, it's extremely fast, it has enough memory, it's cheap reliable and it have builtin wifi that enables cool features.

I'm sorry but adding new boards is surely something that I will do in the future, but not in the near one.
Hope that you'll find the time to switch to the ESP8266 devices.

Thank you for the kind words and the suggestions 😉 

I'm going to close the issue for now but feel free to reopen it or to reply to this one if you have any other questions/suggestions.

Thanks

**Comment by DrSaad77** [comment]
Thx you very much for your recommendation. I dont doubt it is a powerful board, I will probably give a try to Firefly soft when I will assemble the Wimos + the led board, and it will give me an feedback.
I understand another board is not prim at the moment, you probably working on increase the feature of the project and you got my full support in that way )) and thx you for keeping it in mind for the future, even if it is not in a near once. 
Another idea, is maybe to add a mood switch light, maybe already present maybe not, maybe I missed it, anyway I am recommendating it 😉
Plus a sound equalizer is not a bad idea also 😁
Anyway they are just ideas, so sure you ll manage them and step by strep grow the project, you got full full support and trust for the future of the project.

**Comment by sblantipodi** [comment]
@DrSaad77 thanks you very much, I always appreciate suggestions and most of your suggestions will be added in the next releases.
if you like the project, don't forget to cast a star and if you want to join our community on discord:
https://discord.com/invite/aXf9jeN

**Comment by KweezyCode** [comment]
any updates?

**Comment by sblantipodi** [comment]
@KweezyCode Luciferin support for newer boards is widely increased in the recent months,
do you have an interest on a particular board?

**Comment by KweezyCode** [comment]
> @KweezyCode Luciferin support for newer boards is widely increased in the recent months, do you have an interest on a particular board?

arduino nano does not work, only with lightpack software
