### ISSUE TITLE
[Feature request]: Tray icon and minimize to tray on Linux

### ISSUE THREAD

**Issue by sorcererlc** [sblantipodi/firefly_luciferin#234]
### Is your feature request related to a problem? Please describe

Not really a problem, more an inconvenience of having the Luciferin window open all the time.

### Describe the solution you'd like

I would like to have a tray icon and the ability to hide the main window on Linux like I had on Windows.

**Comment by sblantipodi** [comment]
Hi @sorcererlc,
thanks for the suggestion.

This is something I've wanted to do for a long time, adding the `keep` label until implemented.

**Comment by sblantipodi** [comment]
Just to inform you @sorcererlc that this feature has been implemented and it will be released in the next release.

if you don't want to wait for the next release you can download the nighly build here:
https://github.com/sblantipodi/firefly_luciferin/actions/runs/11023705193

**Comment by sorcererlc** [comment]
I downloaded and ran the nightly build but there's no tray icon being created.

If it helps with anything, I'm using GTK to generate a system tray widget.

Another thing I just thought of that would be nice is a configuration option to minimize to tray instead of quitting when closing the main window. This would be a great help for people who don't have window decorations like a title bar and a minimize button.

**Comment by sblantipodi** [comment]
mmm... on Ubuntu 24.04, GNOME 26 (X11 and Wayland) and KDE Plasma the tray icon works as in Windows, 
if you click the X, it simply minimize to tray.

if this is not the case on your system it means that your system returns false to this method call
[SystemTray.isSupported()](https://docs.oracle.com/javase/8/docs/api/java/awt/SystemTray.html)

probably the GTK widget you are using does not notify the OS that the tray is supported with it.

can you remember me your OS details please? Are you using GNOME?

if you want to try it I have created another build that "skip the check if tray is supported" and act like if it's suppoted.
[1can you see if this improves the situation?](https://github.com/sblantipodi/firefly_luciferin/actions/runs/11036717202)

if yes, next step would be to understand why the widget you are using does not notify the OS about the tray support.

**Comment by sorcererlc** [comment]
I am running Hyprland on Arch Linux and I am using [ags](https://github.com/Aylur/ags) for the system tray widget.

The latest build throws an exception when starting
```
[Instance #1] 19:14:02.565 [JavaFX Application Thread] INFO  org.dpsoftware.FireflyLuciferin - ** Log level -> INFO **
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:893)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.
	at java.desktop/java.awt.SystemTray.getSystemTray(Unknown Source)
	at org.dpsoftware.gui.TrayIconManager.initTray(TrayIconManager.java:237)
	at org.dpsoftware.FireflyLuciferin.start(FireflyLuciferin.java:261)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
	... 1 more
```

**Comment by sblantipodi** [comment]
what are the programs that you are running with AGS that works well?
does it support only GTK programs?

it's weird that Java isn't able to detect the tray support.

**Comment by sorcererlc** [comment]
Electron apps like Slack and Discord work. Also Vivaldi, Steam, OpenRGB and Telegram.
As far as I know they're all written in C/C++ but I don't know what bindings they use to integrate with the system tray.

**Comment by sblantipodi** [comment]
that package has been merged in plasma so it shouldn't be too bad, you could consider to create an image of your disk if you are worried about "breaking things", install the package and revert back if something broke :)

I don't think that it's a JavaFX problem it's just that Java (AWT) uses xembed instead of SNI for the tray icon.

**Comment by sorcererlc** [comment]
It has indeed been merged into plasma but that's the problem, there's no individual package available anymore. The AUR [package](https://linux-packages.com/aur/package/xembed-sni-proxy-git) is marked deprecated.

Just for laughs I tried installing it anyway and both yay and paru complained that "No AUR package found for xembed-sni-proxy-git". I also tried building it from [source](https://github.com/KDE/plasma-workspace/tree/master/xembed-sni-proxy) but that also failed as I'm missing some X libraries.

**Comment by sblantipodi** [comment]
I haven't answered yet because I'm still trying to find a solution for systems that lacks xembed.

Tray icon is managed by AWT and not by JavaFx and AWT is still using xembed.

**Comment by sorcererlc** [comment]
No worries, take your time.
For now I just have a rule in hyprland to banish that window to a workspace I don't use :)

**Comment by sblantipodi** [comment]
stay tuned ;)

![Screenshot From 2024-11-11 21-33-09](https://github.com/user-attachments/assets/86cceafd-41d9-4985-8301-54f93b6f066e)

**Comment by sblantipodi** [comment]
hi @sorcererlc, 
new build is available [here](https://github.com/sblantipodi/firefly_luciferin/actions/runs/11852897418)

this build uses the latest possible notification system on Linux 
(`libayatana-appindicator` or `libappindicator`) if you don't have it, you can install it with pacman.

there is another new feature.
if you have `libnotify` installed (pretty all linux distros bundles it), notification are now less intrusive using the OS notification system (less dialogs, more notifications).

if you want to give it a try, you know where to download it, if you prefer to wait for the final release, it's fine :)

**Comment by sorcererlc** [comment]
Hi there,

I installed the new build and so far it works great. The AGS/GTK system tray now picks up Luciferin's icon, the menu works and the main window starts minimized.
![image](https://github.com/user-attachments/assets/ade6fe8d-198b-4296-90fa-59d7fa332de8)

Since moving to Linux I haven't seen many notifications from Luciferin. On Windows I was getting the frame rate popup quite often while gaming but on Linux it doesn't seem to complain very much. I do have libnotify installed as a dependency for swaync so we'll see how it goes.

I'll keep trying to break it over the next days but so far I have to say great job :)

**Comment by sblantipodi** [comment]
if you want to try notifications it's very simple:
- go to settings
- devices tab
- click manage satellites
- click the + button

it should complain that it lacks a valid ip address. this is just a method to test the notifications :)

thank you for the feedback and the continued support sorcererlc, it's much appreciated 👍

**Comment by sorcererlc** [comment]
Nice. Notification integration works too :)
![image](https://github.com/user-attachments/assets/32c33b16-9341-40f3-830e-8185b8c596b7)

**Comment by sblantipodi** [comment]
ok. thank you very much :)

**Comment by Nyxis0** [comment]
Could you guys guide me how to get this working in Arch?

**Comment by sorcererlc** [comment]
@Nyxis0 While it is possible to install .deb packages on Arch it's generally not recommended because it can cause conflicts with pacman. The recommended method is to clone the source and create a PKGBUILD that can then be installed using pacman.

Personally, I installed from the .rpm package. I just extracted it and copied the files to /opt. I also copied the .desktop file to /usr/share/applications so it would get picked up by the the app launcher.

**Comment by sblantipodi** [comment]
sorcerlc is obviously more competent than me on the arch side, so listen to him :D 
I use Linux for 30 years in various flavours but never used Arch...

I am trying to understand how to publish the app on flatpak and snap but it will take some time.
In the mean time I would be very happy to add a specific build for arch but I need to understand how to do it first :)

**Comment by sorcererlc** [comment]
I would say that my competency with Arch is mediocre at best. I've only running using Arch for the past two months or so. But I did learn a lot about it and Linux in general during this time, by necessity really, since Arch just left me with a TTY and told me to deal with it :D

I haven't messed with PKGBUILD yet but according to the [wiki](https://wiki.archlinux.org/title/PKGBUILD) it should be relatively straight forward since you already have the build system in place. If you're using Github Actions or some other CI system you should even be able to provide a -bin release so people don't have to install build dependencies and build from source every time if they only want so use stable releases.
Major bonus points if you also decide to publish to AUR :)

I'd be happy to help with testing if you decide to try it.
Maybe we should move this to another issue so we don't completely hijack the initial topic?

**Comment by sblantipodi** [comment]
> Maybe we should move this to another issue so we don't completely hijack the initial topic?

agree

**Comment by sblantipodi** [comment]
@sorcererlc a new release is out...
if you like Snap Store or Flathub you can try it.

https://snapcraft.io/install/fireflyluciferin/arch
https://flathub.org/apps/org.dpsoftware.FireflyLuciferin

Happy holidays sorcererlc :)

**Comment by sorcererlc** [comment]
Now this is a nice present! :)

I installed the flatpak and it seems to be working great.
I did run into that old issue with the main window not being displayed until I removed the existing configuration file but that's easily fixed.


Happy holidays :)

**Comment by sblantipodi** [comment]
Happy holidays sorcererlc :)
