### ISSUE TITLE
Feature Request - Change position of LED #1

### ISSUE THREAD

**Issue by Teleportist** [sblantipodi/firefly_luciferin#24]
Firstly, thanks for taking the time to produce this neat, compact, ambilight solution.

REQUEST: Please consider adding a feature to make it possible to specify the position of LED #1.

My LEDs are installed starting from the bottom-left corner of the TV, when viewed from the front.
And they run the complete length along the bottom. A typical wall mount configuration.

So using the firefly software currently means the the light pattern produced is always out of sync with the TV image by 15 positions.

MY SETUP
Running Firefly Lucifer in on a Windows 10 PC.

Running Glowworm Luciferin firmware on a ESP 8266 D1 microcontroller.
Connected via MQTT (server running within Home Assistant on a Raspberry Pi 3 B+).

**Comment by sblantipodi** [comment]
@Teleportist thanks for opening this issue. this is a highly requested feature so I will implement it as soon as possible.
I leave this issue open until a release will close it.
Thank you!

**Comment by sblantipodi** [comment]
@Teleportist the latest 1.5.0 release implements the features you requested. 😉
