### ISSUE TITLE
Dual Monitor Support

### ISSUE THREAD

**Issue by pandaboy6621** [sblantipodi/firefly_luciferin#31]
I would like to be able to put a giant rectangle of LEDs around my two monitors and run them off of one wemos d1 minis. This way both of my monitors can have this Ambilight.

**Comment by sblantipodi** [comment]
Ok, time for multi monitor support is arrived.
As asked in #27 I am going to add multi monitor support.

> There is two way to implement multi monitor:
> 1) One arduino per monitor with it's own LED strip
> 2) One arduino for all the monitors with a daisy chained LED strip

I like more the first solution, it's really more efficient in terms of "arduino power" and it's surely the fastest and better responsive one. This is why I am going to implement this solution first.

Second solution will be implemented in the future.

Pandaboy is a good member of the community, for others who wants to be informed on new releases, 
don't forget to cast a star here on github and watch the project, 
or if you want, you can join the community on discord here:

[![Discord](https://img.shields.io/discord/747247942074892328.svg?label=&logo=discord&logoColor=ffffff&color=7389D8&labelColor=6A7EC2)](https://discord.gg/aXf9jeN)

**Comment by sblantipodi** [comment]
multiple monitors support has been added in the latest release but you will need one microcontroller per monitor.

thanks for opening the issue.
