### ISSUE TITLE
Discord Server?

### ISSUE THREAD

**Issue by pandaboy6621** [sblantipodi/firefly_luciferin#32]
I was wondering If a discord server could be made for support and sharing projects. (sry I don't know how to tag these)

**Comment by sblantipodi** [comment]
@pandaboy6621 we have a small but great community on Discord.
Here the invitation 😃 
https://discord.gg/aXf9jeN

thank you for your interest in the project, if you like the project don't forget to cast a star here on GitHub.

I am going to close this issue, feel free to open a new one or to join our Discord server!

**Comment by pandaboy6621** [comment]
Thanks
