### ISSUE TITLE
DDUPL mode doesn't work anymore on v1.7.2

### ISSUE THREAD

**Issue by sashayohan** [sblantipodi/firefly_luciferin#34]
3440x1440

Release v1.7.2
DDUPL mode doesn't work anymore on this version

I'm using the version v1.6.8
DDUPL mode works on this version

Glow Worm Luciferin firmware v4.4.1

**Comment by sblantipodi** [comment]
hi @sashayohan can you give me more information please? 

- what do you mean for it doesn't work anymore? do you see some light?
-are you using the light or the full firmware?
-is there some erros in the log? you can find them in Documents/FireflyLuciferin/logs
- have you tried restarting the ESP?
- if you click start and then info during capturing, do you see something that says: capturing at 30fps, consuming at 30 fps or something similar?
- can you give me a screenshot of the devices tab? please give me two screenshot to show me the table completely. one on the side left and one on the right side.

thank you

**Comment by sblantipodi** [comment]
@sashayohan  
I need some more info please...
1) what software do you use to flash the ESP? ESP Home Flashar wipe you ESP memory before flashing, this is what we want now.
2) do you have the same problem with both Full and Light firmware?
3) why you have such a low framerate? are you running many many LEDs? how many LEDs are you running?
4) we need to debug it more... Close Luciferin PC software.
please go into your Documents\FireflyLuciferin\ folder. Inside that folder you'll find a FireflyLuciferin.yaml file. Edit it.
Scroll down to the bottom of the file, at the end you'll find a extendedLog: false, change it to extendedLog: true
now start Firefly Luciferin and start capturing until the problem happen.
Please zip all the Documents\FireflyLuciferin\logs folder and send me it. I need only the logs folder, not the other folders.
5) please send me your FireflyLuciferin.yaml file, in there you'll have your MQTT password, mqtt is on local network so there is no problem in having it there but if you don't want to share your pwd with me, just remove the password before sending me it

**Comment by RonaldHiemstra** [comment]
Maybe I can help, I am not sure if my issue is the same as @sashayohan...
I don't have the firmware running yet, but I do receive the MQTT stream.
With version  v1.7.2, after running for a short while, I get a `Framerate error` popup: `Firefly Luciferin is out of sync`.
After pressing OK, the stream stops. (note: after pressing `Cancel`, it seems to work 😄)

See [FireflyLuciferin.log](https://github.com/sblantipodi/firefly_luciferin/files/5793072/FireflyLuciferin.log)

**Comment by sblantipodi** [comment]
@RonaldHiemstra thanks for joining the discussion, I appreciate it.
`Firefly Luciferin` PC software and `Glow Worm Luciferin` firmware are made to work togheter.
Once you start capturing the screen, PC software sends color information to the firmware and the firmware sends back some information to the pc software just to inform the PC software that all is running well.

If you don't have the firmware "up and running", PC software shows that errors because there is no one that sends back the information of the stream.

Please install the firmware on an ESP (FULL firmware if you are running MQTT) and feel free to open an issue if you still have the problem.

Thanks for the feedback Ronald.

**Comment by sblantipodi** [comment]
ok I identified the problem.
it seems that some ESP8266 aren't able to handle 1M baud rate.
I'm going to release a fix that will permit the user to select the best baud rate for their microcontroller.

For people who are experiencing problems at 1million baud rate should try 500K.

**Comment by sashayohan** [comment]
Hi. Sorry for the long answer

I use D1 Mini
ESPHome-Flasher-1.3.0-macOS.zip
GlowWormLuciferinFULL_ESP8266_firmware.bin

Logs and screenshots in the archive
https://www90.zippyshare.com/v/FzVPAke3/file.html

**Comment by sblantipodi** [comment]
@sashayohan thank you for the answer. 
archive is not accessible. 

but can you describe the problem more in depth? do you have some errors?
it never work or it work with another screen capture method?

if you want I attach a beta firmware and a beta version of Firefly Luciferin,
if you want to give it a try it may work better.

https://cdn.discordapp.com/attachments/797659327438782465/798408437011972136/First_Try_logs.7z

**Comment by sashayohan** [comment]
DDUPL v1.6.8 nice works. DDUPL v1.7.2 it works, but the image capture is shifted
The other capture methods work.

https://drive.google.com/file/d/10UsMFhqGvPu7phFdxqEwB6184I3c7ZCZ/view?usp=sharing

**Comment by sblantipodi** [comment]
@sashayohan archive is not public, I'm still not able to download it.

**Comment by sashayohan** [comment]
forgot to open access)
https://drive.google.com/file/d/10UsMFhqGvPu7phFdxqEwB6184I3c7ZCZ/view?usp=sharing

**Comment by sblantipodi** [comment]
@sashayohan 
I was able to reproduce the problems. Next release (in few days hopeully) will fix this problem.
Users that reports problems and helps in finding the solution are gold members here. xD
I will include your name in the release just to thank you!
