### ISSUE TITLE
can you please add support for simple HDMI capture card instead of computer monitor.

### ISSUE THREAD

**Issue by Grappa2020** [sblantipodi/firefly_luciferin#35]
it will be nice to use it on Raspberry Pi running Ubuntu / Debian between a Receiver and TV

https://www.aliexpress.com/item/1005001699389687.html?spm=a2g0o.productlist.0.0.4e19667eqHlfrW&algo_pvid=4b8478e1-66e0-426d-ae39-24f78176c16e&algo_expid=4b8478e1-66e0-426d-ae39-24f78176c16e-17&btsid=0b0a556c16109014741123448ef653&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

**Comment by sblantipodi** [comment]
Hi @Grappa2020, thanks for your interest in the Luciferin Project.
Anything may happen one day but this is not on the roadmap currently.

Thank you
Davide
