### ISSUE TITLE
Cant start Linux Desktop app

### ISSUE THREAD

**Issue by partizanna** [sblantipodi/firefly_luciferin#39]
## Firefly Luciferin version  
fireflyluciferin-1.8.7-1-x86_64

## Describe the bug

The desktop app failed to start with "Please configure the app." message.

## To Reproduce 

$ /opt/fireflyluciferin/bin/FireflyLuciferin 
11:18:31,616 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
11:18:31,616 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
11:18:31,617 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/opt/fireflyluciferin/lib/app/FireflyLuciferin-jar-with-dependencies.jar!/logback.xml]
11:18:31,624 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@2e4b8173 - URL [jar:file:/opt/fireflyluciferin/lib/app/FireflyLuciferin-jar-with-dependencies.jar!/logback.xml] is not of type file
11:18:31,669 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
11:18:31,672 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:18:31,674 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
11:18:31,721 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - This appender no longer admits a layout as a sub-component, set an encoder instead.
11:18:31,721 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
11:18:31,721 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
11:18:31,721 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
11:18:31,725 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE-ROLLING]
11:18:31,729 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@118394766 - setting totalSizeCap to 10 MB
11:18:31,730 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@118394766 - Archive files will be limited to [2 MB] each.
11:18:31,731 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@118394766 - No compression will be used
11:18:31,731 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@118394766 - Will use the pattern logs/archived/app.%d{yyyy-MM-dd}.%i.log for the active file
11:18:31,732 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@17046283 - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/archived/app.%d{yyyy-MM-dd}.%i.log'.
11:18:31,732 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@17046283 - Roll-over at midnight.
11:18:31,738 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@17046283 - Setting initial period to Sun Feb 07 11:18:16 CET 2021
11:18:31,739 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:18:31,742 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE-ROLLING] - Active log file name: /home/partizan/Documents/FireflyLuciferin/logs/FireflyLuciferin.log
11:18:31,742 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE-ROLLING] - File property is set to [/home/partizan/Documents/FireflyLuciferin/logs/FireflyLuciferin.log]
11:18:31,743 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.dpsoftware] to INFO
11:18:31,743 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.dpsoftware] to false
11:18:31,743 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE-ROLLING] to Logger[org.dpsoftware]
11:18:31,743 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
11:18:31,743 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE-ROLLING] to Logger[ROOT]
11:18:31,743 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.dpsoftware] to DEBUG
11:18:31,743 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.dpsoftware] to false
11:18:31,743 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[org.dpsoftware]
11:18:31,743 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:18:31,744 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@5bd03f44 - Registering current configuration as safe fallback point

11:18:31.746 [main] DEBUG org.dpsoftware.JavaFXStarter - Starting default instance

(FireflyLuciferin:399762): Gtk-WARNING **: 11:18:31.902: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(FireflyLuciferin:399762): Gtk-WARNING **: 11:18:31.902: Theme parsing error: gtk.css:73:35: The :prelight pseudo-class is deprecated. Use :hover instead.
11:18:32.010 [JavaFX Application Thread] INFO  o.dpsoftware.managers.StorageManager - /home/partizan/Documents/FireflyLuciferin already exists
11:18:32.011 [JavaFX Application Thread] ERROR o.dpsoftware.managers.StorageManager - Error reading config file, writing a default one.
11:18:32.301 [JavaFX Application Thread] INFO  o.dpsoftware.managers.StorageManager - /home/partizan/Documents/FireflyLuciferin already exists
11:18:32.301 [JavaFX Application Thread] ERROR o.dpsoftware.managers.StorageManager - Error reading config file, writing a default one.
11:18:32.360 [JavaFX Application Thread] ERROR org.dpsoftware.FireflyLuciferin - 
file:/opt/fireflyluciferin/lib/app/FireflyLuciferin-jar-with-dependencies.jar!/org/dpsoftware/gui/linuxSettings.fxml

11:18:32.360 [JavaFX Application Thread] ERROR org.dpsoftware.FireflyLuciferin - Please configure the app.

## Expected behavior  
app starts up

**Comment by sblantipodi** [comment]
Hi, thanks for opening this issue, this is a known issue and I have fixed it in this pull request #37 

I am going to release the fix today or tomorrow.

Thanks!

**Comment by sblantipodi** [comment]
please don't forget that your user dir Documents should be writable.

**Comment by partizanna** [comment]
It created the directory in Documents, and it also writing logs, so rights should be OK 

The log contains only the errors from the output above.
I also tested this on 2 systems - my main Archlinux desktop, and in a latest Linux Mint VM, both had the exact same output.

**Comment by sblantipodi** [comment]
ok, as soon as I release the pull request, github will automatically close the issue, I'm pretty sure that it will solve your problem but feel free to reopen it in case you need it.
