### ISSUE TITLE
[Feature request]: indication of the beginning of the LED strip

### ISSUE THREAD

**Issue by whakru** [sblantipodi/firefly_luciferin#58]
### Is your feature request related to a problem? Please describe

It is very inconvenient to indent the first LED.

Очень не удобно делать отступ первого светодиода.

### Describe the solution you'd like

Add a check mark in the corners to indicate the start of the LED strip.  For example, bottom left, bottom right, and so on.
 Can be implemented as a selection in the corner of the monitor on the settings screen.

Добавьте галочку в углах, указывающий начало светодиодной ленты. Например слева снизу, справа снизу и так далее.
Можно реализовать в виде выбора в углу монитора на экране настроек.

**Comment by sblantipodi** [comment]
I agree with this... will do, thanks!

**Comment by whakru** [comment]
> I agree with this... I will do it, thanks!

You can make a drop-down list next to the direction.

**Comment by sblantipodi** [comment]
this feature request will be closed on the next release.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/4722227/150691747-6d527deb-8958-4bfd-8dad-5d91546b8985.png">


there is now an indication of the corner where the first led is.

**Comment by whakru** [comment]
very cool! 
 just do not remove the possibility of a shift (in numbers).  you can add a "manual shift" item where the user manually selects the desired shift of the LEDs.

**Comment by sblantipodi** [comment]
@whakru sure, there will be a combobox that let you select
"bottom left, bottom center, bottom right, upper right, upper left".

once selected an item Firefly automatically calculate the correct LED offset but you can manually enter your own value if you prefer. :)

**Comment by sblantipodi** [comment]
closed by #54
