### ISSUE TITLE
[Feature request]: add language packs

### ISSUE THREAD

**Issue by whakru** [sblantipodi/firefly_luciferin#59]
### Describe the solution you'd like

Would love to see the language packs.  So that languages ​​can be added.

Хотелось бы увидеть языковые пакеты. Чтобы можно было добавлять языки.

**Comment by sblantipodi** [comment]
I am adding the language pack. 

The translation file can be downloaded from GitHub:
https://github.com/sblantipodi/firefly_luciferin/blob/effects/src/main/resources/messagebundle_en.properties

there are some "words" that doesn't need a translation, in Italian for example there is no reason to translate words like "download", "start", "stop", "letterbox", "pillarbox"...
if you feel that some words does not need a translation, just skip the translation.

it is very simple to translate the file. all the phrases or words are in one row. 
put long phrases in one row without the carriage return. software will indent the text correctly. 
this is an example of a row that needs the translations:

before the translation:
fxml.save=Save

After the translation:
fxml.save=Speichern

as you can see, you need to translate only the part after the "=" and not the one before.

I'm searching for someone who can translate in Deutsch, Russian, Français, Español...
I have translated it in Italian... 

There are two users on Discord that are trying to translate the file in Deutsch and Russian.

I'll keep this issue updated if someone else join the tranlsation. :)

At the moment there are no one translating in Français and Español.

**Comment by sblantipodi** [comment]
Deutsch has been translated by @Maaaaarc, we need Russian, Français, Español...

**Comment by sblantipodi** [comment]
UPDATE:
thanks @kopidoo for the Hungarian translation.
We still need Russian, Français, Español.

**Comment by whakru** [comment]
> UPDATE:
> thanks @kopidoo for the Hungarian translation.
> We still need Russian, Français, Español.

Russian

https://drive.google.com/file/d/1-GuOq2OXFu5hWBTADdKzsyNsbYm-dHcQ/view?usp=sharing

Translated as best I could, there may be inaccuracies.
Probably someone will fix it in the future.
Some phrases did not translate, I do not understand their meaning.

**Comment by sblantipodi** [comment]
> sync check could you explain what this means? does it check the firmware version in the app and on the device? or will it check the frames per second and compare them with the app? There is a misunderstanding in the translation.

thank you for pointing it out...
Sync check means that the app checks if the firmware is in sync with the app.
if not, it shows an error.

if the app (firefly) captures at 60FPS and the firmware (glowworm) consumes at 50FPS there is an error if sync check is enabled.

if the app (firefly) captures at 60FPS and the firmware (glowworm) consumes at 60FPS there is no error.

**Comment by morganflint** [comment]
I have just finished the Spanish translation in the attached file "messagebundle_es.properties.txt" (don't know if the naming scheme is correct, just changed "en" to "es").
I've translated virtually all the messages, just left untranslated rows 54 to 61 as I'm not aware of the context and the words "letterbox" and "pillarbox", as there isn't a proper Spanish word for these concepts (even Spanish Wikipedia keeps them in English)
[messagebundle_es.properties.txt](https://github.com/sblantipodi/firefly_luciferin/files/8152927/messagebundle_es.properties.txt)

**Comment by sblantipodi** [comment]
we only luck French now

**Comment by sblantipodi** [comment]
> I've translated virtually all the messages, just left untranslated rows 54 to 59 as I'm not aware of the context and the words "letterbox" and "pillarbox", as there isn't a proper Spanish word for these concepts

same here, I haven't translated that words in Italian. I don't think that we have a right word for that.

Thank you so much @morganflint

**Comment by sblantipodi** [comment]
with french translations we close this issue...
thank you all.

**Comment by sblantipodi** [comment]
@Linjieqiang 
sure that you can! thanks for the interest, 
take your time and I'm looking forward for your PR.

To add a new language it's very simple and you need to do the following:
1) Add the language in the `messagebundle.properties` file, for example:
`enum.language.zh=中國人`
2) Add the language in the `Enums.java` file, for example:
```
    public enum Language implements LocalizedEnum {
        DE("enum.language.de"),
        EN("enum.language.en"),
        ES("enum.language.es"),
        FR("enum.language.fr"),
        HU("enum.language.hu"),
        IT("enum.language.it"),
        RU("enum.language.ru"),
        ZH("enum.language.zh");
        private final String language;

        Language(String language) {
            this.language = language;
        }

        public String getValue() {
            return language;
        }
    }
```
3) Create the `messagebundle_en.properties` file into `messagebundle_zh.properties` and start with the translations...

If you have any questions feel free to ask :)

Thanks!!!
