### ISSUE TITLE
[Feature request]: add device connection status.

### ISSUE THREAD

**Issue by whakru** [sblantipodi/firefly_luciferin#60]
### Is your feature request related to a problem? Please describe

Today I came home and found that the backlight was not working.  The app indicates fps and wifi power.  It turned out that there was no food, but it is not written about it anywhere.

сегодня пришел домой и обнаружил что подсветка не работает. В приложении указывается fps и мощность wifi. Оказалось небыло питания, но об этом нигде не написано.

### Describe the solution you'd like

add connection status to the app.  So that you can understand whether the module is online or not.  I use Wifi full udp, without mqtt (although I think it will be useful for mqtt too).

добавить статус подключения в приложение. Чтобы можно было понимать онлайн ли модуль или нет. Я использую Wifi full udp, без mqtt (хотя думаю и для mqtt это будет полезно)

**Comment by sblantipodi** [comment]
> It turned out that there was no food, but it is not written about it anywhere.

can you elaborate this please? what do you mean for there was no food?

**Comment by whakru** [comment]
> can you elaborate this please? what do you mean for there was no food?

Sorry, this is a translator, I did not notice)
There was no power.
wemos was not powered up.

**Comment by sblantipodi** [comment]
this seems a power issue, not a luciferin issue, am I wrong? :)

**Comment by whakru** [comment]
> this seems a power issue, not a luciferin issue, am I wrong? :)

when there is no power on the module.  For some reason, the application showed that everything is fine.

maybe it has something to do with a bug:
#62
