### ISSUE TITLE
[Feature request]: quick change of effects in the tray.

### ISSUE THREAD

**Issue by whakru** [sblantipodi/firefly_luciferin#61]
### Describe the solution you'd like

it would be nice to have a quick change of effects right in the tray by pressing the right mouse button.

было бы не плохо иметь быструю смену эффектов прямо в трее по нажатию правой кнопки мыши.

**Comment by sblantipodi** [comment]
hello, thanks for opening the issue,
there are so many effects, how long should be the tray icon menu?

**Comment by whakru** [comment]
> hello, thanks for opening the issue,
there are so many effects, how long should be the tray icon menu?

Really. Maybe you can make a scrolling list?
Maybe make a selection "Favorites"?

**Comment by sblantipodi** [comment]
@whakru next release will implement this feature request.

**Comment by morganflint** [comment]
Another possibility to avoid cluttering the tray icon menu would be to use hierarchical menus like the one in the picture. For example, we could have "effects/music/VU Meter-Stereo VU Meter-Screen capture-Rainbow music", "effects/Misc/Twinkle-Rainbow-Mixed rainbow-Chase rainbow-Solid rainbow
![TryIconSubMenus](https://user-images.githubusercontent.com/10438424/167598622-e8da5e6b-4b6c-4f8e-9e89-1d8860401ccc.jpg)
"

**Comment by sblantipodi** [comment]
> Another possibility to avoid cluttering the tray icon menu would be to use hierarchical menus like the one in the picture. For example, we could have "effects/music/VU Meter-Stereo VU Meter-Screen capture-Rainbow music", "effects/Misc/Twinkle-Rainbow-Mixed rainbow-Chase rainbow-Solid rainbow ![TryIconSubMenus](https://user-images.githubusercontent.com/10438424/167598622-e8da5e6b-4b6c-4f8e-9e89-1d8860401ccc.jpg) "

Thank you @morganflint for your continued support, I appreciate it.
Yes I had that in mind, will do it that way. :)
