### ISSUE TITLE
[Feature request]: Basic colour and grayscale calibration

### ISSUE THREAD

**Issue by kopidoo** [sblantipodi/firefly_luciferin#64]
### Is your feature request related to a problem? Please describe

Gray level representation with RGB LEDs might be a pain in the neck. A grayscale calibration feature would be a big step ahead.
The RGB and CMY colour calibration is also a good feature that helps to get the display colours closer to the LED colours. If the wall behind the display is other than white, it can show some special colours with ambilight.

### Describe the solution you'd like

Since I am only a consumer with minor colour corection knowledge, my description might be basic level.
The colour calibration should have the RGBCMY colours as a separate variable. (for white there is the temperature option) Adjustment should work the way like this:
- clicking on each base colour the following pops up
-- pre-stored calibration image on the border similar like the LED test image for the correct grabber input
-- a window in the middle with a colour palette and a hue field (saturation and brightness)
- playing with the adjustments should be stored with a store/save button
- After calibrating, the grabber uses the corrected colours 

A 10 point Greyscale calibration with 10% percent steps with a similar method as described above to make the grays look OK.

I don't know how the white temperature will affect the others. It seems a bit challenging to code.

### Describe alternatives you've considered

RGBW strips could help the grays but the need of base colour calibration is almost a must.

**Comment by sblantipodi** [comment]
this is going to be implemented in the next release. thanks for the good idea @kopidoo
