### ISSUE TITLE
Failed to launch JVM

### ISSUE THREAD

**Issue by jimbok8** [sblantipodi/firefly_luciferin#7]
I have downloaded the latest release.
When I double click on `Fast Screen Capture.exe`  I get the following error.
"Failed to launch JVM"
Jim

**Comment by sblantipodi** [comment]
@jimbok8 thanks for opening the issue.
are you using a 32bit Windows?
What version of Windows?

Thanks

**Comment by sblantipodi** [comment]
@jimbok8 I think that i discovered the issue.
That error is thrown when there is no microcontroller connected to the PC. Do you have a microcontroller connected via the serial port?
