### ISSUE TITLE
[Bug]: The new application does not see the esp with the old firmware.

### ISSUE THREAD

**Issue by whakru** [sblantipodi/firefly_luciferin#79]
### Firefly Luciferin version

v2.7.3

### Glow Worm Luciferin version

Glow Worm Luciferin (V5.3.1)

### Firmware type

FULL

### What is the stream method?

USB

### How to reproduce

The new v2.7.3 application does not see esp with firmware (V5.3.1). it is not very convenient since you will have to connect usb to update.
I thought he would offer to update the firmware in esp via wifi

**Comment by sblantipodi** [comment]
ok, as said in the other issue, please try to reproduce the problem, some temporary issue may have occurred.

**Comment by whakru** [comment]
problem solved
#77 
https://github.com/sblantipodi/firefly_luciferin/issues/77#issuecomment-1169693298
