### ISSUE TITLE
[Feature request]: Smoothing feature

### ISSUE THREAD

**Issue by kopidoo** [sblantipodi/firefly_luciferin#80]
### Is your feature request related to a problem? Please describe

Fast changes on screen could cause too fast changes in LED colour and/or brightness just like a strobe.
On a longer time this can be disturbing.

### Describe the solution you'd like

A linear smoothing feature could be inplemented.
This smoothing interpolates the previous to the target colors in a moving time window. (It is a history of relevant LED-color frames)
This moving time window can be adjustable to set the ideal smoothing.
Higher value (longer time frame) has smoother effect but the LED will be less responsive to quick changes.
Lower value (shorter time frame) has less smoothing but more responsive.

### Describe alternatives you've considered

A decay based smoothing could be an advanced version of smoothing.
Here a decay power variable and a weighted moving average is introduced. The decay power is used with every new frame that comes to the time window. Older frames have less weight/power.

**Comment by sblantipodi** [comment]
Very interesting, this is something that will be implemented in the future. Adding keep label.

**Comment by lordraiden** [comment]
I think this one is very interesting, sometimes while playing the leds change colour very fast and is a little bit distracting, with fast pacing games I usually disable the dynamic lightning.

**Comment by sblantipodi** [comment]
@lordraiden 
@kopidoo 

I have started developing this feature request and the result seems very promising.

if you want to partecipate in doing some beta test please let me know it.

no firmware update needed, only "Firefly Luciferin" PC software update needed.
