### ISSUE TITLE
[Feature request]: aspect ratio synced on multiple instances

### ISSUE THREAD

**Issue by Maaaaarc** [sblantipodi/firefly_luciferin#83]
Hello here again,

So as you may know, I have 3 different screens (3 ESPs), which capture the same Image, which means that the LEDs all react, to the same image, just in a different place.

My little problem is when I watch a video, where the aspect ratio is not recognized correctly
or I want to set it manually, I have to change it individually for each one, which means it takes a long time,
and if I want to change it several times, because I sometimes watch a lot of short videos, this is unpractical.

### Describe the solution you'd like

Therefore, my suggestion would be that the aspect ratio is synchronised, as long as the instances use the same monitor as the source.

### Describe alternatives you've considered

Or another option which I don't think is possible yet, that you can use the home assistant integration, to adjust the aspect ratio and not just read it out.
Because then I can put 3 Buttons on my dashboard, which change that for all of them.

Hope you can understand what I mean and that would be actionable. 

**_Suggestion first submitted via Discord_**

**Comment by sblantipodi** [comment]
as discussed on Discord, this feature request will include another feature,
tooltips on the tray icons will show the device name in use, this will help in better understanding what is the device controlled by the luciferin instance.
