### ISSUE TITLE
[Feature request]: Resume MQTT stream from Firefly, triggered by MQTT

### ISSUE THREAD

**Issue by jypma** [sblantipodi/firefly_luciferin#88]
### Is your feature request related to a problem? Please describe

MQTT control of GlowWorm LEDs through home assistant doesn't seemlessly combine with Firefly sending streaming LED data.

My use case:
- I'd like the LEDs to match Kodi playing movies on my TV. This works great (using MQTT stream).
- I'd also be able to control the LEDs through MQTT (from Home Assistant) when not watching movies. This works great too.
- However, after sending static on/off/color/effect commands through MQTT, Firefly's MQTT stream stops. I have to manually restart the Firefly MQTT stream to have it follow Kodi again

### Describe the solution you'd like

I have not investigated in detail which MQTT (or other) commands Firefly sends when starting the stream. It's also unclear whether the stream itself is interrupted when taking over Glow Worm control through MQTT.

It might be as simple as documenting the MQTT command to "resume listening to the incoming MQTT stream" on Glow Worm.

Otherwise, such an MQTT command should be introduced.

Home Assistant can then instruct Glow Worm to listen to the stream when Kodi starts a movie.

If it turns out Firefly i stopping the stream in this case, a restart should be triggerd in Firefly, potentially by listening to MQTT. 

### Describe alternatives you've considered

I'm currently manually restarting the stream in Firefly, each time I start a movie.

**Comment by sblantipodi** [comment]
Hi @jypma, thanks for your intereste in the project.

[Home assistant integration](https://github.com/sblantipodi/firefly_luciferin/wiki/Home-Automation-configs) has a ready to use package that gives you some hints on the MQTT topic to use for the various commands.

The solid effect button:
<img width="333" alt="image" src="https://user-images.githubusercontent.com/4722227/188838525-6f04305a-a7c1-48bb-abaa-141c0884d8e4.png">

triggers an automation that starts and stops the bias light effect (screen capture).

The topic used for this is: 
`lights/glowwormluciferin`

the payload you can use to start and stop is this:
`{"state":"ON","startStopInstances":"STOP"}`
`{"state":"ON","startStopInstances":"PLAY"}`

hope it helped.

**Comment by jypma** [comment]
Thanks for the explanation! I had indeed added the included `home_assistant_luciferin_package.yaml` to Home Assistant already.

By updating my Kodi automations to set the "Solid Effect" input boolean to `false` after starting a movie, and to `true` after it, the light is working perfectly in both modes.

Coincidentally, it somehow _also_ solved the issue of `Firefly` crashing with "Cannot connect to Glow Worm" at times. I'll report back if this happens again.

Have you considered having Glow Worm make use of Home Assistant MQTT auto-discovery? It would just require the ESP to put a persistent message into MQTT on startup.

**Comment by sblantipodi** [comment]
@jypma sorry for the late reply and thanks for the answer.

> Have you considered having Glow Worm make use of Home Assistant MQTT auto-discovery? It would just require the ESP to put a persistent message into MQTT on startup.

Adding MQTT auto-discorvery for HA is something that I want to add in the next releases but I need to understand how to do it in a good way.
If you have some suggestions is really welcomed.

Feel free to add a feature request for it if you want to see implemented in the next future.

thanks!
