### ISSUE TITLE
[Feature request]: Series led connection (satellites)

### ISSUE THREAD

**Issue by cr333d** [sblantipodi/firefly_luciferin#97]
### Describe the solution you'd like

I want to connect my led table lamp(via data line) to right led col led of the monitor leds or top and bottom row.So that it replicates the colours.If the data single be transfer over wifi or bluetooth to another receiver it will be awesome then we can keep any lamp or any led device far away and it will replacate the colours from the col or row leds strips which are there at the back of the monitor. I am not sure if the mods will understood or not.You can check what govee T2 has done with ambilight.

**Comment by sblantipodi** [comment]
I will add it in a future release.

**Comment by cr333d** [comment]
Thank you very much
