### ISSUE TITLE
[Feature request]: Update Home Assistant integration package for MQTT breaking changes

### ISSUE THREAD

**Issue by bcameron21** [sblantipodi/firefly_luciferin#99]
### Is your feature request related to a problem? Please describe

Home Assistant release 2022.06 introduced changes to MQTT configuration, and the old configuration was deprecated in release 2022.09

Defining manually configured MQTT entities directly under the respective platform keys (e.g., fan, light, sensor, etc.) is deprecated, and support will be removed in Home Assistant Core 2022.9.

Manually configured MQTT entities should now be defined under the mqtt configuration key in configuration.yaml instead of under the platform key.

### Describe the solution you'd like

The code in the integration package luciferin.yaml needs to be updated.

**Comment by sblantipodi** [comment]
closed by [#47](https://github.com/sblantipodi/glow_worm_luciferin/pull/47)

thanks for reporting  @bcameron21 
new package as been updated.

https://github.com/sblantipodi/glow_worm_luciferin/blob/master/home_assistant_luciferin_package.yaml
